Stream: Stream::Socket Class Reference
Stream::Socket Class Reference
Socket resource.
#include "Stream/Socket.hpp"
Classes
struct Address
struct Exception
Public Member Functions
Socket ()
Construct a IPv4 TCP Socket resource.
Socket (Address const &address, int backlog)
Construct a TCP server Socket.
Socket (Address const &address)
Construct a TCP client Socket.
Socket (Socket const &)=delete
Socket (Socket &&other) noexcept
Socket & operator= (Socket &&other) noexcept
~Socket ()
void bind (Address const &address)
Bind this Socket to an address.
void listen (int backlog)
Put this Socket into the listening state.
Socket accept () const
Accept a new client connection.
void connect (Address const &address)
Connect to a server at the address.
int getMSS () const
Get the maximum segment size of the TCP connection.
timeval getRecvTimeout () const
void setRecvTimeout (timeval timeout)
timeval getSendTimeout () const
void setSendTimeout (timeval timeout)
Input & read (void *dest, std::size_t size)
std::size_t readSome (void *dest, std::size_t size)
Input & operator>> (auto &t)
template<Char C>
Input & operator>> (std::basic_string< C > &s)
Input & operator>> (Char auto *s)
Output & write (void const *src, std::size_t size)
std::size_t writeSome (void const *src, std::size_t size)
virtual void flush ()
Output & operator<< (std::nullptr_t)
Output & operator<< (auto const &t)
template<Char C>
Output & operator<< (std::basic_string< C > const &s)
Output & operator<< (Char auto const *s)
Friends
void swap (Socket &a, Socket &b) noexcept
Detailed Description
Socket resource.
Definition at line 13 of file Socket.hpp.
Constructor & Destructor Documentation
Socket() [1/4]
Stream::Socket::Socket ()
Construct a IPv4 TCP Socket resource.
Exceptions
Socket::Exception
See also
socket()
Creates a socket resource. If socket() system call fails, it throws a Socket::Exception.
Definition at line 19 of file Socket.cpp.
        : Socket{socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)}
{}
Socket() [2/4]
Stream::Socket::Socket (Address const & address, int backlog)
Construct a TCP server Socket.
Parameters
[in] address Address to be bound to accept incoming connections
[in] backlog Maximum length of pending connections queue
Exceptions
Socket::Exception
See also
socket()
bind()
listen()
Definition at line 28 of file Socket.cpp.
        : Socket{}
{
    if (::bind(mDescriptor, &address, sizeof(struct sockaddr_in)) ||
        ::listen(mDescriptor, backlog)) {
        auto const errc{static_cast<std::errc>(errno)};
        if (close(mDescriptor) < 0)
            perror(nullptr);
        throw Exception{std::make_error_code(errc)};
    }
}
References bind(), and listen().
Socket() [3/4]
Stream::Socket::Socket (Address const & address) explicit
Construct a TCP client Socket.
Parameters
[in] address Address to connect
Exceptions
Socket::Exception
See also
socket()
connect()
Definition at line 44 of file Socket.cpp.
        : Socket{}
{
    if (::connect(mDescriptor, &address, sizeof(struct sockaddr_in))) {
        auto const errc{static_cast<std::errc>(errno)};
        if (close(mDescriptor) < 0)
            perror(nullptr);
        throw Exception{std::make_error_code(errc)};
    }
}
References connect().
Socket() [4/4]
Stream::Socket::Socket (Socket && other) noexcept
Definition at line 55 of file Socket.cpp.
{ swap(*this, other); }
~Socket()
Stream::Socket::~Socket ()
See also
close()
perror()
stdin, stdout, stderr
Closes the socket resource. If the close() system call fails, it writes the description of the error to the standard error stream.
Definition at line 76 of file Socket.cpp.
{
    if (mDescriptor > 2 && close(mDescriptor) < 0)
        perror(nullptr);
}
Member Function Documentation
operator=()
Socket & Stream::Socket::operator= (Socket && other) noexcept
Definition at line 63 of file Socket.cpp.
{
    swap(*this, other);
    return *this;
}
bind()
void Stream::Socket::bind (Address const & address)
Bind this Socket to an address.
Parameters
[in] address Address to be bound
Exceptions
Socket::Exception
See also
bind()
Definition at line 112 of file Socket.cpp.
{ ExpectNNeg(::bind(mDescriptor, &address, sizeof(struct sockaddr_in))); }
References bind().
Referenced by Socket(), and bind().
listen()
void Stream::Socket::listen (int backlog)
Put this Socket into the listening state.
Parameters
[in] backlog Maximum length of pending connections queue
Exceptions
Socket::Exception
See also
listen()
Definition at line 119 of file Socket.cpp.
{ ExpectNNeg(::listen(mDescriptor, backlog)); }
References listen().
Referenced by Socket(), and listen().
accept()
Socket Stream::Socket::accept () const
Accept a new client connection.
Returns
Socket
Exceptions
Socket::Exception
See also
accept()
Definition at line 126 of file Socket.cpp.
{ return Socket{::accept(mDescriptor, nullptr, nullptr)}; }
References accept().
Referenced by accept().
connect()
void Stream::Socket::connect (Address const & address)
Connect to a server at the address.
Parameters
[in] address Address to connect
Exceptions
Socket::Exception
See also
connect()
Definition at line 133 of file Socket.cpp.
{ ExpectNNeg(::connect(mDescriptor, &address, sizeof(struct sockaddr_in))); }
References connect().
Referenced by Socket(), and connect().
getMSS()
int Stream::Socket::getMSS () const
Get the maximum segment size of the TCP connection.
Returns
Maximum segment size in bytes
Exceptions
Socket::Exception
See also
getsockopt()
TCP_MAXSEG
Definition at line 141 of file Socket.cpp.
{
    int mss{0};
    socklen_t optlen{sizeof mss};
    ExpectNNeg(getsockopt(mDescriptor, IPPROTO_TCP, TCP_MAXSEG, &mss, &optlen));
    return mss;
}
getRecvTimeout()
timeval Stream::Socket::getRecvTimeout () const
Definition at line 150 of file Socket.cpp.
{
    timeval recvTimeout{0, 0};
    socklen_t optlen{sizeof recvTimeout};
    ExpectNNeg(getsockopt(mDescriptor, SOL_SOCKET, SO_RCVTIMEO, &recvTimeout, &optlen));
    return recvTimeout;
}
setRecvTimeout()
void Stream::Socket::setRecvTimeout (timeval timeout)
Definition at line 159 of file Socket.cpp.
{ ExpectNNeg(setsockopt(mDescriptor, SOL_SOCKET, SO_RCVTIMEO, &timeout, sizeof timeout)); }
getSendTimeout()
timeval Stream::Socket::getSendTimeout () const
Definition at line 163 of file Socket.cpp.
{
    timeval sendTimeout{0, 0};
    socklen_t optlen{sizeof sendTimeout};
    ExpectNNeg(getsockopt(mDescriptor, SOL_SOCKET, SO_SNDTIMEO, &sendTimeout, &optlen));
    return sendTimeout;
}
setSendTimeout()
void Stream::Socket::setSendTimeout (timeval timeout)
Definition at line 172 of file Socket.cpp.
{ ExpectNNeg(setsockopt(mDescriptor, SOL_SOCKET, SO_SNDTIMEO, &timeout, sizeof timeout)); }
read()
Input & Stream::Input::read (void * dest, std::size_t size) inherited
Definition at line 7 of file InOut.cpp.
    {
    while (size) {
        auto outl{readBytes(reinterpret_cast<std::byte*>(dest), size)};
        reinterpret_cast<std::byte*&>(dest) += outl;
        size -= outl;
    }
    return *this;
} catch (Exception& exc) {
    exc.mDest = dest;
    exc.mSize = size;
    throw;
}
readSome()
std::size_t Stream::Input::readSome (void * dest, std::size_t size) inherited
Definition at line 22 of file InOut.cpp.
{
    if (size) do {
        if (auto outl{readBytes(reinterpret_cast<std::byte*>(dest), size)})
            return outl;
    } while (true);
    return 0;
}
write()
Output & Stream::Output::write (void const * src, std::size_t size) inherited
Definition at line 57 of file InOut.cpp.
    {
    while (size) {
        auto inl{writeBytes(reinterpret_cast<std::byte const*>(src), size)};
        reinterpret_cast<std::byte const*&>(src) += inl;
        size -= inl;
    }
    return *this;
} catch (Exception& exc) {
    exc.mSrc = src;
    exc.mSize = size;
    throw;
}
writeSome()
std::size_t Stream::Output::writeSome (void const * src, std::size_t size) inherited
Definition at line 72 of file InOut.cpp.
{
    if (size) do {
        if (auto inl{writeBytes(reinterpret_cast<std::byte const*>(src), size)})
            return inl;
    } while (true);
    return 0;
}
flush()
void Stream::Output::flush () virtual inherited
Reimplemented in Stream::File.
Definition at line 82 of file InOut.cpp.
{}
operator<<()
Output & Stream::Output::operator<< (std::nullptr_t) inherited
Definition at line 85 of file InOut.cpp.
{
    flush();
    return *this;
}
Friends And Related Function Documentation
swap
void swap (Socket & a, Socket & b) friend
Definition at line 59 of file Socket.cpp.
{ std::swap(a.mDescriptor, b.mDescriptor); }